spring.application.name=iMirly

# Usar base de datos en memoria (H2) para que arranque sin errores
spring.datasource.url=jdbc:h2:mem:imirlydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
