spring.application.name=iMirly
spring.datasource.url=jdbc:postgresql://localhost:5432/imirly_db
spring.datasource.username=user_imirly
spring.datasource.password=password_imirly
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true